name: Build the client extensions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: unzip
      run: unzip wsClient.pmp -d ./wsClient
    - name: sed
      run: sed -i "s/http:\/\/localhost:8000/https:\/\/4672dcd4.worldsprites-source.pages.dev/g" wsClient/project.json
    - name: zip
      run: zip -r wsClient.pmp wsClient
    - name: remove
      run: rm -r wsClient
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Build client extensions"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    